CREATE DATABASE "World_power_plant"
CREATE TABLE public.world_plant_list
(
  id SERIAL,
  PLANT_URL VARCHAR(100),
  PLANT_NAME VARCHAR(100),
  PLANT_DESIGN_CAPACITY_MWE VARCHAR(100),
  PLANT_COUNTRY VARCHAR(100),
  PLANT_STATE VARCHAR(100),
  PLANT_COUNTRY_ASSIGNED_IDENTIFICATION_NUMBER VARCHAR(100),
  PLANT_EFFICIENT_AND_IMPACT VARCHAR(100),
  PLANT_OVERALL_RATING VARCHAR(100),
  PLANT_GEO_ASSIGNED_ID_NUMBER VARCHAR(100),
  PLANT_CURRENCY VARCHAR(100),
  PLANT_LATITUDE VARCHAR(100),
  PLANT_LONGITUDE VARCHAR(100),
  PLANT_TYPE_OF_PLANT VARCHAR(100),
  PLANT_LOCATION VARCHAR(100),
  PLANT_FUEL_TYPE_SECONDARY VARCHAR(100),
  PLANT_TYPE_OF_OWNERSHIP VARCHAR(100),
  PLAMT_TYPE VARCHAR(100),
  TYPE_URL VARCHAR(100),
  geopoint VARCHAR(100),
  PRIMARY KEY (id)
)

--select count(*) from world_plant_list
